# -*- coding: utf-8 -*-
"""EmployeeData.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/19-nE98KoG1VuRGR0FrHIDme2jRlx-L31
"""

import pandas as pd
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker()

# Generate 100 employee records
data = []
for i in range(1, 101):
    emp_id = f"E{str(i).zfill(3)}"
    full_name = fake.name()
    job_title = fake.job()
    department = random.choice(["IT", "Marketing", "HR", "Sales", "Analytics", "Finance"])
    employment_status = random.choice(["Full-time", "Part-time", "Contractor"])
    hire_date = fake.date_between(start_date="-5y", end_date="today").strftime("%Y-%m-%d")
    work_email = f"{full_name.lower().replace(' ', '.')}@company.com"
    contact_number = fake.phone_number()

    # Compensation & Salary
    if employment_status in ["Full-time", "Contractor"]:
        annual_salary = f"${random.randint(40000, 120000)}"
        hourly_rate = "N/A"
    else:
        hourly_rate = f"${random.randint(15, 35)}/hour"
        annual_salary = "N/A"
    pay_frequency = random.choice(["Monthly", "Bi-weekly", "Weekly"])
    bank_account = f"XXXX-XXXX-XXXX-{fake.random_number(4)}"
    overtime_hours = random.randint(0, 20)
    bonuses = f"${random.randint(0, 10000)}" if random.random() > 0.7 else "$0"
    deductions = random.choice(["Health Insurance ($200)", "401(k) 5%", "None"])

    # Leave Balances
    pto_balance = random.randint(0, 20)
    sick_balance = random.randint(0, 15)
    vacation_used = random.randint(0, pto_balance)
    vacation_remaining = pto_balance - vacation_used
    leave_requests = f"{fake.date_this_year()}: Vacation (Pending)" if random.random() > 0.5 else "None"
    unpaid_leave = f"{fake.date_this_year()} (3 days)" if random.random() > 0.8 else "None"

    # Tax Information (masked)
    ssn = f"XXX-XX-{fake.random_number(4)}"
    tax_status = random.choice(["Single", "Married", "Head of Household"])
    federal_allowances = random.randint(0, 3)
    ytd_tax = f"${random.randint(5000, 30000)}"
    prev_tax = f"W-2: ${random.randint(45000, 110000)}"

    # ... Continue for other sections (Benefits, Time & Attendance, etc.) ...

    data.append({
        "Employee ID": emp_id,
        "Full Name": full_name,
        "Job Title": job_title,
        "Department": department,
        "Employment Status": employment_status,
        "Hire Date": hire_date,
        "Work Email": work_email,
        "Contact Number": contact_number,
        "Annual Salary": annual_salary,
        "Hourly Rate": hourly_rate,
        "Pay Frequency": pay_frequency,
        "Bank Account": bank_account,
        "Overtime Hours": overtime_hours,
        "Bonuses": bonuses,
        "Deductions": deductions,
        "PTO Balance": pto_balance,
        # ... Add remaining fields ...
    })

df = pd.DataFrame(data)
df.to_csv("dummy_employee_data.csv", index=False)

pip install faker

